site_name: Numberscope
nav:
    - Overview: README.md
    - User Guide:
          - Introduction: doc/user_guide.md
          - ... | flat | src/visualizers/*
    - Extending:
          - doc/extending.md
          - doc/running-from-source.md
          - doc/making-a-visualizer.md
    - Contributing:
          - doc/contributing.md
          - doc/visual-studio-code-setup.md
          - doc/working-with-pm.md
    - Other Information:
          - ... | flat | doc/*.md
docs_dir: doc
site_dir: dist/doc
theme:
    name: readthedocs
    prev_next_buttons_location: both
    sticky_navigation: false
extra_css: [doc/css/theme_override.css, doc/css/coordinate.css]
extra_javascript: [doc/themejs/theme_override.js]
plugins:
    - awesome-pages
    - search
    - semiliterate:
          exclude_extensions: ['.jpg', '.ttf', '.ico', 'LICENSE.md']
          ignore_folders: [node_modules, dist, coverage]
          include_extensions: ['.png', '.css', 'override.js']
          merge_docs_dir: false
          semiliterate:
              - pattern: '\.ts' # Standard in-code markup
                extract:
                    start: '^\s*/\*\*+\W?md\b' # Opening like /** md
                    stop: '^\s*\*\*/\s*$' # closing **/ by itself on a line
              - pattern: 'App.vue$' # Grab CSS needed to coordinate styles
                destination: ../doc/css/coordinate.css
                extract:
                    start: 'style'
                    stop: 'main'
markdown_extensions:
    - pymdownx.superfences
